apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tb9ibbroz-nodejs
  janus-idp.io/tekton: tb9ibbroz-nodejs
  backstage.io/kubernetes-id: tb9ibbroz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tb9ibbroz-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
